Спринт 9. Попытка 1
romaozna/java-filmorate pull request #1
Opened 2022-12-12 13:45 UTC by romaozna

2022-12-13 13:01 UTC, Fleaman777 requested changes

2022-12-13 13:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
молодец, что вынес валидацию в отдельный метод - разделение ответсвенности
и внутри метода все правильно, на каждую ошибку, свой месседж

2022-12-13 13:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                    }
немного сложноватая логика (внутри ифов свитчи...) для обычных методов добавления о обновления, 

для начала, можно просто напрямую сделать эти опреацию внутри методов create и update

а там дальше вся эта логика все равно переедет в спецальный для этого слой (service)

2022-12-13 13:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                    }
здесь аналогичные комментарии как  и в FilmController

2022-12-13 13:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Past
здорово, что часть валидаци сделал через аннотации, это существенно улучшает восприятие кода, 
главное не забывать это тестировать

2022-12-13 13:01 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    }
хорошие тесты, покрывают все необходимые кейсы

2022-12-13 13:01 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +                .build();
часть общей логики по созданию юзера, можно было бы вынести в метод beforeEach

аналагично и в FilmControllerTest тестах

2022-12-13 13:01 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +        String longDescription = fillString(201, 'r');
хороший подход к генерации тестового описания

2022-12-13 13:25 UTC, romaozna commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
Спасибо!

2022-12-13 13:46 UTC, romaozna commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +                .build();
не совсем понимаю, тогда придется final у полей класса убирать, в @BeforeEach создавать фильм через билдер и уже в каждом отдельном тесте через сеттер задавать нужное поле. Но тогда шаблон билдер свой смысл теряет. Можешь конкретнее сказать, какая часть могла бы уйти в @BeforeEach?

2022-12-13 14:45 UTC, romaozna commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                    }
Принял, действительно перемудрил

2022-12-14 14:47 UTC, Fleaman777 approved these changes

2022-12-14 14:47 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    Film film;
в тестах тоже хорошо бы придерживаться инкапсуляции

2022-12-14 14:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    final private String login;
оно конечно и так работает, но лучше в начале прописывать модификатор доступа, а потом все остальные ключевые слова

2022-12-14 14:47 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +                .build();
ну да, все верно, с файнал полями то, что я написал, не пройдет, 
так что можешь оставить как есть

2022-12-14 14:56 UTC, merged