Спринт 10. Попытка 1
romaozna/java-filmorate pull request #2
Opened 2022-12-23 11:14 UTC by romaozna

2022-12-24 11:15 UTC, Fleaman777 requested changes

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        }
эту логику проверки лучше вынести в сервис, что бы контроллер отвечал только за получаение о отправку запросов

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(required = false) Optional<String> name) {
в целом, нет необходимости оборачивать входящие параметры в Optional, в данном случае эта конструкция только утяжеляет логику,
0 и null здесь вполне будут подходящие значения 

аналагично в похожих местах

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> findAll(
хм, что-то не нахожу в спецификации/задании этого эндпоинта, 
он нужен, или это ты просто от себя добавил ?

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @DeleteMapping("/{filmId}")
и вот этот эндпоинт в задании тоже не видел,

посмотри какие еще эндпоинты не упомянуты в задании, если есть такие, то можешь смело их удалить)

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return new ArrayList<>(filmStorage.getAll(p));
хороший подход с ограничением списка фильмов

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    }
попробуй написать часть этого метода, а модет и весь, через стрим 
если получится, то должно будет выглядеть еще лучше

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    }
метод валидации, если он используеься только в сервисе, лучше сделать private и переместить бдиже к концу класса (после public методов)

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/Storage.java
> +public interface Storage<K, V> {
хороший подход с дженериками

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return films.values().stream().sorted(Comparator.comparingInt(Film::getId)).collect(Collectors.toList());
хорошо было бы для восприятия, если отформотировать  в стрим формате (каждый метод на отдельной строчке)

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    }
отличный метод что бы сделать его через стрим

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/friends/InMemoryFriendsStorage.java
> +}
аналогичные комментарии, как 2 предыдущих

2022-12-24 11:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/likes/InMemoryLikesStorage.java
> +        return likesByCondition;
и здесь тоже можно через стрим

2022-12-24 11:15 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +
за исправленные тесты, согласно новым требованиям, респект

2022-12-25 10:21 UTC, romaozna commented on src/main/java/ru/yandex/practicum/filmorate/storage/likes/InMemoryLikesStorage.java
> +        return likesByCondition;
спасибо за подсказку, почему сам до этого не дошел не пойму

2022-12-25 15:01 UTC, romaozna commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    }
да, этот метод был написан еще до тестов в Postman, в которых я обнаружил, что в теле запроса есть поле rate. После добавления поля rate в класс Film этот метод нужно было рефакторить, да.

2022-12-26 15:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/likes/InMemoryLikesStorage.java
> +        return likesByCondition;
со временем и не такие вещи будешь замечать :)

2022-12-26 15:22 UTC, Fleaman777 approved these changes

2022-12-26 15:22 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilms();
супер, 
нравится, когда в контроллере нет логики и онр выглядит примерно так :)

2022-12-26 15:22 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        }
момент на будущее, подобную валидацию, можно выносить в отдельный компонент, 

так и код в самом контроллере не загромождается, + отдельный компонент легче тестировать

2022-12-26 15:22 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                .collect(Collectors.toList());
красота!

2022-12-27 09:02 UTC, merged