Add database
romaozna/java-filmorate pull request #3
Opened 2023-01-20 13:52 UTC by romaozna

2023-01-21 08:52 UTC, Fleaman777 requested changes

2023-01-21 08:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    String name;
поля должны быть private

2023-01-21 08:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        return genre.get();
у Optional есть хороший метод orElseThrow отлично бы сюда вписался, 
и весь этот метод можно было бы сократить до 1 строки

аналагично в др похожих местах

2023-01-21 08:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                "LIMIT ?";
💪

2023-01-21 08:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    }
вместо конуструктора можно было бы использовать ломбок аннотацию @RequiredArgsConstructor

меньше бойлерплейт кода - лучше восприятие

аналагично в др местах

2023-01-21 08:52 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/UserStorageTest.java
> +}
хорощие тесты

2023-01-21 08:52 UTC, Fleaman777 commented on .gitignore
нужно еще созлать файл README и добавить в него ссылку на картину схемы бд

2023-01-21 11:58 UTC, romaozna commented on .gitignore
Странно, что ты их не видишь. Сейчас поправлю, там новых ручек нет для жанров и мпа, так как это еще для промежуточного спринта заданием было

2023-01-22 10:14 UTC, Fleaman777 approved these changes

2023-01-22 10:14 UTC, Fleaman777 commented on .gitignore
а да, теперь увидел, спасибо)

2023-01-23 06:20 UTC, merged